version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=calendar_reminder
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"
    command:
      - rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
