name: Release Backend

on:
  push:
    branches:
      - release_be
  pull_request:
    branches:
      - release_be

jobs:
  release_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t calendar_reminder:latest .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag calendar_reminder:latest $DOCKER_USERNAME/calendar_reminder:latest
          docker push $DOCKER_USERNAME/calendar_reminder:latest